ALTER TABLE appuser
    ADD COLUMN IF NOT EXISTS show_dob       BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE appuser
    ADD COLUMN IF NOT EXISTS show_location  BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE appuser
    ADD COLUMN IF NOT EXISTS show_gender    BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE appuser
    ADD COLUMN IF NOT EXISTS show_interests BOOLEAN NOT NULL DEFAULT TRUE;
